apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 2
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: bitnami/postgresql:17.5.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: password
                  name: postgresql-config
