apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "15"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
  database.properties: |
    url=psql://postgresql1.com
    time=UTC
